<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net4.5.2</TargetFramework>
    <ApplicationIcon>Resources/Icons/Autumn.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackAsTool>False</PackAsTool>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.ImGui.Backends.GLFW" Version="1.0.18" />
    <PackageReference Include="SharpYaml" Version="2.1.5" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input.Extensions" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Tomlyn" Version="0.20.0" />
  </ItemGroup>

  <ItemGroup>
    <DBFiles Include="$(MSBuildProjectDirectory)\Resources\RedPepper-ClassDataBase\Data\*" />
    <ModifierFiles Include="$(MSBuildProjectDirectory)\Resources\Autumn-ClassModifiers\Modifiers\*" />
    <Icons Include="$(MSBuildProjectDirectory)\Resources\Icons\*" />
    <Themes Include="$(MSBuildProjectDirectory)\Resources\Themes\*" />
  </ItemGroup>

  <Target Name="CopyTasksBuild" AfterTargets="Build">
    <Copy SourceFiles="@(ModifierFiles)" DestinationFolder="$(OutDir)\Resources\Modifiers\" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(DBFiles)" DestinationFolder="$(OutDir)\Resources\ClassDB\" SkipUnchangedFiles="True" />
    <Copy SourceFiles="@(Icons)" DestinationFolder="$(OutDir)\Resources\Icons\" SkipUnchangedFiles="True" />
    <Copy SourceFiles="@(Themes)" DestinationFolder="$(OutDir)\Resources\Themes\" SkipUnchangedFiles="True" />
  </Target>

  <Target Name="CopyTasksPublish" AfterTargets="Publish">
    <Copy SourceFiles="@(ModifierFiles)" DestinationFolder="$(PublishDir)\Resources\Modifiers\" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(DBFiles)" DestinationFolder="$(PublishDir)\Resources\ClassDB\" SkipUnchangedFiles="True" />
    <Copy SourceFiles="@(Icons)" DestinationFolder="$(PublishDir)\Resources\Icons\" SkipUnchangedFiles="True" />
    <Copy SourceFiles="@(Themes)" DestinationFolder="$(PublishDir)\Resources\Themes\" SkipUnchangedFiles="True" />
  </Target>

  <ItemGroup>
    <Content Include="$(MSBuildProjectDirectory)\Resources\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" DestinationFolder="Resources" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BYAMLSharp">
      <HintPath>..\Libraries\BYAMLSharp\BYAMLSharp\bin\Debug\net8.0\BYAMLSharp.dll</HintPath>
    </Reference>
    <Reference Include="NARCSharp">
      <HintPath>..\Libraries\NARCSharp\NARCSharp\bin\Debug\net8.0\NARCSharp.dll</HintPath>
    </Reference>
    <Reference Include="SceneGL">
      <HintPath>..\Libraries\SceneGL\SceneGL\bin\Debug\net7.0\SceneGL.dll</HintPath>
    </Reference>
    <Reference Include="SPICA">
      <HintPath>..\Libraries\SPICA\SPICA\bin\Debug\net6.0\SPICA.dll</HintPath>
    </Reference>
    <Reference Include="TinyFileDialogsSharp">
      <HintPath>..\Libraries\tinyfiledialogs\src\bin\Debug\net7.0\TinyFileDialogsSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
